final0/basic_app/urls.py
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

app_name='basic_app'

urlpatterns=[
	path('school_list/',views.SchoolListView.as_view(),name='list'),
	path('detail/<int:pk>',views.SchoolDetailView.as_view(),name='detail'),
	path('create/',views.SchoolCreateView.as_view(),name='create'),
	path('update/<int:pk>',views.SchoolUpdateView.as_view(),name='update'),
	path('createst/',views.StudentCreateView.as_view(),name='createst'),
	path('delete/<int:pk>',views.SchoolDeleteView.as_view(),name='delete')
]

final0/final0/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('basic_app/',include('basic_app.urls',namespace='basic_app'))
]

final0/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
	name=models.CharField(max_length=256)
	principal=models.CharField(max_length=256)
	location=models.CharField(max_length=256)
	def __str__(self):
		return self.name
	def get_absolute_url(self):
		return reverse("basic_app:detail",kwargs={'pk':self.pk})

class Student(models.Model):
	name=models.CharField(max_length=256)
	age=models.PositiveIntegerField()
	school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

	def __str__(self):
		return self.name

final0/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,
	ListView,DetailView,
	CreateView,UpdateView,DeleteView)
from . import models
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
class IndexView(TemplateView):
	template_name='index.html'


class SchoolListView(ListView):
	model = models.School
	context_object_name='Schools'
	template_name='basic_app/school_list.html'
class SchoolDetailView(DetailView):
	context_object_name='School_detail'
	model = models.School
	template_name = 'basic_app/school_details.html'
class SchoolCreateView(CreateView):
	fields=('name','principal','location')
	model= models.School
	template_name='basic_app/school_forms.html'
	success_url=reverse_lazy("basic_app:list")
class SchoolUpdateView(UpdateView):
	fields=('name','principal')
	model=models.School
	template_name='basic_app/school_update.html'
class SchoolDeleteView(DeleteView):
	model=models.School
	template_name='basic_app/school_delete.html'
	success_url=reverse_lazy("basic_app:list")

class StudentCreateView(CreateView):
	fields=('name','age','school')
	model= models.Student
	success_url=reverse_lazy("basic_app:list")
	template_name='basic_app/student_forms.html'

final0/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Base</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'basic_app:list' %}">School</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
    </ul>
  </div>
</nav>
<div class="container">
  {% block body_block %}
  {% endblock %}
</div>



</body>
</html>

final0/basic_app/templates/basic_app/school_delete.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
	<h2>Delete {{school.name}}</h2>
<form method="POST">
	{% csrf_token %}
	<input type="submit" class="btn btn-danger" value='Delete'>
	<a class="btn btn-primary" href="{% url 'basic_app:list'  %}">Cancel</a>
</form>
</form>

{% endblock %}

final0/basic_app/templates/basic_app/school_details.html
{% extends 'basic_app/school_list.html' %}

{% block body_block %}

<div class="jumbotron">
	{% if School_detail %}
	<h1>Welecome to the school detail page</h1>
	<h2>School Detail:</h2>
	<p>Name: {{School_detail.name}}</p>
	<p>Principal: {{School_detail.principal}}</p>
	<p>Location {{School_detail.location}}</p>
	<h3>Students: </h3>

	{% for student in School_detail.students.all %}
	<p>{{student.name}} who is {{student.age}} years old.</p>
	{% endfor %}
	{% else %}
	<p>There is no details</p>
	{% endif %}
</div> 
<div class="container">
	<a class="btn btn-warning" href="{% url 'basic_app:update' pk=School_detail.pk %}">Update</a>
	<a class="btn btn-danger" href="{% url 'basic_app:delete' pk=School_detail.pk %}">Delete</a>
	<a class="btn btn-primary" href="{% url 'basic_app:createst' %}">Add Student</a>
</div>


{% endblock %}

final0/basic_app/templates/basic_app/school_forms.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<h1>
	{% if not form.instance.pk %}
	Create School
	{% else %}
	Update School
	{% endif %}
</h1>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" class="btn btn-primary" value="Create">
</form>

{% endblock %}

final0/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<h1>welcome to a list of all the schools!</h1>

  {% if Schools %}
<ol>
  {% for school in Schools %}
    <h2><li><a href="{% url 'basic_app:detail' school.id %}">{{school.name}}</a></li></h2>
  {% endfor %}
</ol>
{% else %}
    <p>There are no Schools in the library.</p>
{% endif %}
<a class="btn btn-primary" href="{% url 'basic_app:create' %}">Create New School</a>
{% endblock %}

final0/basic_app/templates/basic_app/school_update.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" class="btn btn-warning" value="Update">
</form>
{% endblock %}

final0/basic_app/templates/basic_app/student_forms.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}

<h1>
	{% if not form.instance.pk %}
	Create School
	{% else %}
	Update School
	{% endif %}
</h1>
<form method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" class="btn btn-primary" value="Create">
</form>

{% endblock %}

final0/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Base</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <ul class="navbar-nav mr-auto">
    <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">School</a></li>
    <li class="nav-item active">
      <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
  </ul>


</nav>

  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>
</body>
</html>

final0/templates/index.html
{% extends "base.html" %}

	{% block body_block %}
		<h1>Home Page!</h1>		
	{% endblock %}